# Generated by Django 2.2.7 on 2021-08-05 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200325_1811'),
        ('biz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnership',
            old_name='biz_address_detail_1',
            new_name='address_detail',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='active',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='biz_address_detail_2',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='biz_code',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='biz_tell',
        ),
        migrations.RemoveField(
            model_name='partnershipuser',
            name='partner_ship',
        ),
        migrations.AddField(
            model_name='partnership',
            name='address_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnerships', to='base.Area', verbose_name='주소 지역'),
        ),
        migrations.AddField(
            model_name='partnership',
            name='business_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='사업자번호'),
        ),
        migrations.AddField(
            model_name='partnership',
            name='business_registration_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='사업자 등록증 사진'),
        ),
        migrations.AddField(
            model_name='partnership',
            name='state',
            field=models.IntegerField(choices=[(0, '승인완료'), (1, '심사중'), (2, '승인반려'), (3, '승인취소'), (4, '휴면상태')], default=1),
        ),
        migrations.AddField(
            model_name='partnership',
            name='tel',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='대표 전화번호'),
        ),
        migrations.AddField(
            model_name='partnershipuser',
            name='partnership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnership_user', to='biz.Partnership', verbose_name='파트너쉽'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=5, verbose_name='협력사코드'),
        ),
        migrations.AlterField(
            model_name='partnershipuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnership_user', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
