# Generated by Django 2.2.7 on 2021-08-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0002_auto_20210805_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='state',
            field=models.IntegerField(choices=[(0, '승인완료'), (1, '심사 중'), (2, '승인반려'), (3, '승인취소'), (4, '휴면')], default=1),
        ),
    ]
