# Generated by Django 2.2.7 on 2021-08-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0003_auto_20210809_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='address_detail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='주소 상세'),
        ),
    ]
