# Generated by Django 2.2.7 on 2021-08-20 11:11

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biz', '0004_auto_20210809_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('accepted_datetime', models.DateTimeField(blank=True, null=True, verbose_name='승인일시')),
                ('rejected_datetime', models.DateTimeField(blank=True, null=True, verbose_name='반려일시')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('campaign_type', models.IntegerField(choices=[(1, '설문조사'), (2, 'CPA')], verbose_name='캠페인 종류')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='게시 시작 일시')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='게시 종료 일시')),
            ],
            options={
                'verbose_name': '캠페인',
                'verbose_name_plural': '캠페인',
            },
        ),
        migrations.CreateModel(
            name='CampaignBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('accepted_datetime', models.DateTimeField(blank=True, null=True, verbose_name='승인일시')),
                ('rejected_datetime', models.DateTimeField(blank=True, null=True, verbose_name='반려일시')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='광고 이미지')),
                ('location', models.IntegerField(choices=[(1, '[APP] 헬퍼홈'), (2, '[APP] 고객홈'), (3, '[WEB] 메인홈')])),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='biz.Campaign', verbose_name='캠페인')),
            ],
            options={
                'verbose_name': '캠페인 배너',
                'verbose_name_plural': '캠페인 배너',
            },
        ),
        migrations.CreateModel(
            name='CampaignQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.PositiveSmallIntegerField(blank=True, default=10, verbose_name='순번')),
                ('question_type', models.CharField(choices=[('radio', '라디오 (1개 선택)'), ('checkbox', '체크박스 (다중 선택)'), ('number', '숫자 입력'), ('text', '단답형 문자'), ('textarea', '장문')], max_length=20, verbose_name='유형')),
                ('name', models.CharField(max_length=250, verbose_name='항목 이름')),
                ('title', models.CharField(max_length=250, verbose_name='질문 제목')),
                ('description', models.TextField(blank=True, verbose_name='질문 설명')),
                ('options', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, verbose_name='선택 항목')),
                ('has_etc_input', models.BooleanField(blank=True, default=False, verbose_name='직접입력(기타) 추가')),
                ('is_required', models.BooleanField(blank=True, default=False, verbose_name='필수 입력 여부')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='biz.Campaign', verbose_name='캠페인')),
            ],
            options={
                'verbose_name': '캠페인 질문',
                'verbose_name_plural': '캠페인 질문',
            },
        ),
        migrations.CreateModel(
            name='CampaignUserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='기기정보')),
                ('app_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='앱정보')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('answer', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='답변')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biz.CampaignBanner', verbose_name='캠페인 배너')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '캠페인 유져 답변 데이터',
                'verbose_name_plural': '캠페인 유져 답변 데이터',
            },
        ),
        migrations.CreateModel(
            name='CampaignUserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='기기정보')),
                ('app_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='앱정보')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('action_type', models.IntegerField(choices=[(0, '노출'), (1, '클릭')], verbose_name='액션 타입')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biz.CampaignBanner', verbose_name='캠페인 배너')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '캠페인 유져 로그',
                'verbose_name_plural': '캠페인 유져 로그',
            },
        ),
        migrations.CreateModel(
            name='PartnershipUserRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('role', models.IntegerField(choices=[(1, '매니저')], default=1)),
            ],
            options={
                'verbose_name': '협력사 유저 관계',
                'verbose_name_plural': '협력사 유저 관계',
            },
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='state',
        ),
        migrations.AddField(
            model_name='partnership',
            name='accepted_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='승인일시'),
        ),
        migrations.AddField(
            model_name='partnership',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성일시'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnership',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화 여부'),
        ),
        migrations.AddField(
            model_name='partnership',
            name='rejected_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='반려일시'),
        ),
        migrations.AddField(
            model_name='partnership',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='code',
            field=models.SlugField(max_length=20, null=True, verbose_name='협력사코드'),
        ),
        migrations.DeleteModel(
            name='PartnershipUser',
        ),
        migrations.AddField(
            model_name='partnershipuserrelation',
            name='partnership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_relations', to='biz.Partnership', verbose_name='파트너쉽'),
        ),
        migrations.AddField(
            model_name='partnershipuserrelation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnership_relations', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='partnership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='biz.Partnership', verbose_name='파트너쉽'),
        ),
    ]
