# Generated by Django 2.2.7 on 2021-08-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0005_auto_20210820_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='code',
            field=models.SlugField(default='', max_length=20, unique=True, verbose_name='협력사코드'),
            preserve_default=False,
        ),
    ]
