# Generated by Django 2.2.7 on 2021-08-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0006_auto_20210820_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='secret',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='api secret'),
        ),
    ]
