# Generated by Django 2.2.7 on 2021-08-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0007_partnership_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignquestion',
            name='question_type',
            field=models.CharField(choices=[('radio', '라디오 (1개 선택)'), ('checkbox', '체크박스 (다중 선택)'), ('number', '숫자 입력'), ('text', '단답형 문자'), ('textarea', '장문'), ('area', '지역'), ('address', '주소'), ('datetime', '날짜와 시간'), ('date', '날짜'), ('time', '시간'), ('files', '파일 첨부')], max_length=20, verbose_name='유형'),
        ),
    ]
