# Generated by Django 2.2.7 on 2021-08-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0008_auto_20210827_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_code',
            field=models.CharField(db_index=True, default='ABCDE', max_length=5, unique=True, verbose_name='캠페인 코드'),
            preserve_default=False,
        ),
    ]
