# Generated by Django 2.2.7 on 2021-09-24 12:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0009_campaign_campaign_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('campaigns', '캠페인'), ('apis', '미션 API'), ('missions', '다중미션')], max_length=20), blank=True, default=list, size=None, verbose_name='사용 서비스'),
        ),
    ]
