# Generated by Django 2.2.7 on 2021-10-05 14:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0010_partnership_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('campaigns', '캠페인'), ('missions', '다중미션'), ('apis', '미션 API')], max_length=20), blank=True, default=list, size=None, verbose_name='사용 서비스'),
        ),
    ]
