# Generated by Django 2.2.7 on 2021-10-14 14:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0012_auto_20211014_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignuserdata',
            name='answer',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, verbose_name='답변'),
        ),
    ]
