# Generated by Django 2.2.7 on 2020-03-03 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnycodeAsIs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anycode', models.CharField(max_length=10, unique=True, verbose_name='AnyCode')),
            ],
        ),
        migrations.CreateModel(
            name='UserAsIs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10, unique=True, verbose_name='UID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_uid', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
        ),
        migrations.CreateModel(
            name='HelperAsIs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_uid', models.CharField(max_length=10, unique=True, verbose_name='H_UID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_h_uid', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
        ),
    ]
