# Generated by Django 2.2.7 on 2020-03-03 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        ('anyman_migration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anycodeasis',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions_anycode', to='missions.Mission', verbose_name='미션'),
        ),
    ]
