# Generated by Django 2.2.7 on 2020-03-26 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anyman_migration', '0004_missionasis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnycodeAsIs',
        ),
    ]
