# Generated by Django 2.2.7 on 2020-02-14 02:20

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missions', '0017_missiontype_charge_rate'),
        ('accounts', '0016_remove_serviceblock_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='금액')),
                ('balance', models.IntegerField(blank=True, verbose_name='잔액')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='일시')),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashes', to='accounts.Helper', verbose_name='회원')),
            ],
            options={
                'verbose_name': '캐쉬 내역',
            },
        ),
        migrations.CreateModel(
            name='CouponTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='쿠폰명')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='쿠폰 설명')),
                ('price', models.IntegerField(verbose_name='포인트')),
                ('code', models.CharField(max_length=6, verbose_name='템플릿 코드')),
                ('is_repetitive_use', models.BooleanField(blank=True, default=True, verbose_name='반복사용 쿠폰')),
                ('active_days', models.PositiveSmallIntegerField(default=30, verbose_name='유효기간일수')),
            ],
            options={
                'verbose_name': '쿠폰 템플릿',
                'verbose_name_plural': '쿠폰 템플릿',
            },
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='금액')),
                ('requested_datetime', models.DateTimeField(auto_now_add=True, verbose_name='요청일시')),
                ('failed_datetime', models.DateTimeField(blank=True, null=True, verbose_name='실패일시')),
                ('done_datetime', models.DateTimeField(blank=True, null=True, verbose_name='처리일시')),
                ('cash', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdraws', to='payment.Cash', verbose_name='캐쉬')),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraws', to='accounts.Helper', verbose_name='헬퍼')),
            ],
            options={
                'verbose_name': '인출',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='금액')),
                ('balance', models.IntegerField(blank=True, verbose_name='잔액')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '포인트 내역',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_method', models.CharField(blank=True, choices=[('Card', '신용카드'), ('Refund', '결제취소')], default='Card', max_length=10, verbose_name='결제방법')),
                ('amount', models.IntegerField(default=0, verbose_name='금액')),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='결제결과')),
                ('payment_id', models.CharField(blank=True, default='', max_length=40, verbose_name='결제모듈 고유 ID')),
                ('authenticated_no', models.CharField(blank=True, default='', max_length=40, verbose_name='승인번호')),
                ('authenticated_datetime', models.DateTimeField(null=True, verbose_name='승인일시')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('failed_datetime', models.DateTimeField(null=True, verbose_name='결제실패 일시')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='missions.Bid', verbose_name='입찰')),
                ('point', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='payment.Point', verbose_name='포인트 사용')),
            ],
            options={
                'verbose_name': '결제',
                'verbose_name_plural': '결제',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_date', models.DateField(verbose_name='유효기한')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('used_datetime', models.DateTimeField(null=True, verbose_name='사용일시')),
                ('point', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coupon', to='payment.Point', verbose_name='포인트 충전')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='payment.CouponTemplate', verbose_name='쿠폰')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='발급 받은 회원')),
            ],
            options={
                'verbose_name': '발급된 쿠폰',
                'verbose_name_plural': '발급된 쿠폰',
            },
        ),
    ]
