# Generated by Django 2.2.7 on 2020-02-17 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cash',
            options={'verbose_name': '캐쉬 내역', 'verbose_name_plural': '캐쉬 내역'},
        ),
        migrations.AlterModelOptions(
            name='point',
            options={'ordering': ('id',), 'verbose_name': '포인트 내역', 'verbose_name_plural': '포인트 내역'},
        ),
        migrations.AlterModelOptions(
            name='withdraw',
            options={'verbose_name': '인출', 'verbose_name_plural': '인출'},
        ),
    ]
