# Generated by Django 2.2.7 on 2020-02-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200217_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupontemplate',
            name='code',
            field=models.CharField(max_length=6, unique=True, verbose_name='템플릿 코드'),
        ),
    ]
