# Generated by Django 2.2.7 on 2020-02-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupontemplate',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='활성화'),
        ),
    ]
