# Generated by Django 2.2.7 on 2020-02-19 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20200218_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdraw',
            options={'verbose_name': '인출요청', 'verbose_name_plural': '인출요청'},
        ),
    ]
