# Generated by Django 2.2.7 on 2020-02-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20200219_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupontemplate',
            name='code',
            field=models.CharField(help_text='반복사용 쿠폰의 경우 여기에 입력한 코드를 그대로 사용하며, 반복사용이 아닌 경우에는 코드 뒤에 일련번호가 붙는 형태로 발급됩니다.', max_length=6, unique=True, verbose_name='템플릿 코드'),
        ),
    ]
