# Generated by Django 2.2.7 on 2020-02-20 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20200219_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='missions.Bid', verbose_name='입찰'),
        ),
    ]
