# Generated by Django 2.2.7 on 2020-03-02 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0010_auto_20200220_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=16, verbose_name='포인트 상품권 코드')),
                ('expire_date', models.DateField(verbose_name='유효기한')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('used_datetime', models.DateTimeField(null=True, verbose_name='사용일시')),
                ('point', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher', to='payment.Point', verbose_name='포인트 충전')),
            ],
            options={
                'verbose_name': '발급된 포인트 상품권',
                'verbose_name_plural': '발급된 포인트 상품권',
            },
        ),
        migrations.CreateModel(
            name='PointVoucherTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='포인트 상품권명')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='포인트 상품권 설명')),
                ('price', models.IntegerField(verbose_name='포인트')),
                ('code', models.CharField(help_text='반복사용 상품권의 경우 여기에 입력한 코드를 그대로 사용하며, 반복사용이 아닌 경우에는 코드 뒤에 일련번호가 붙는 형태로 발급됩니다.', max_length=6, unique=True, verbose_name='템플릿 코드')),
                ('is_repetitive_use', models.BooleanField(blank=True, default=True, verbose_name='반복사용 상품권')),
                ('active_days', models.PositiveSmallIntegerField(default=30, verbose_name='유효기간일수')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '포인트 상품권 템플릿',
                'verbose_name_plural': '포인트 상품권 템플릿',
            },
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='CouponTemplate',
        ),
        migrations.AddField(
            model_name='pointvoucher',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='payment.PointVoucherTemplate', verbose_name='포인트 상품권'),
        ),
        migrations.AddField(
            model_name='pointvoucher',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to=settings.AUTH_USER_MODEL, verbose_name='발급 받은 회원'),
        ),
    ]
