# Generated by Django 2.2.7 on 2020-03-02 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20200302_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='missions.Bid', verbose_name='입찰'),
        ),
    ]
