# Generated by Django 2.2.7 on 2020-03-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='_detail',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='내역 보존'),
        ),
        migrations.AddField(
            model_name='point',
            name='_detail',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='내역 보존'),
        ),
    ]
