# Generated by Django 2.2.7 on 2020-04-26 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_auto_20200331_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='missions.Bid', verbose_name='입찰'),
        ),
    ]
