# Generated by Django 2.2.7 on 2020-07-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_cash_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='memo',
            field=models.TextField(blank=True, default='', verbose_name='메모'),
        ),
    ]
