# Generated by Django 2.2.7 on 2020-08-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_point_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointvouchertemplate',
            name='is_new_users_only',
            field=models.BooleanField(blank=True, default=False, verbose_name='신규 회원만 이용가능'),
        ),
    ]
