# Generated by Django 2.2.7 on 2020-11-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_auto_20201102_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_method',
            field=models.CharField(blank=True, choices=[('POINT', '전액 포인트'), ('CARD', '신용카드'), ('Card', '신용카드 (이니시스)'), ('Refund', '결제취소')], default='Card', max_length=10, verbose_name='결제방법'),
        ),
    ]
