# Generated by Django 2.2.7 on 2020-11-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='canceled_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='해지일시'),
        ),
    ]
