# Generated by Django 2.2.7 on 2021-02-04 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_user_is_ad_allowed'),
        ('payment', '0024_payment_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdraws', to='accounts.BankAccount', verbose_name='은행 계좌'),
        ),
    ]
