# Generated by Django 2.2.7 on 2021-04-21 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0025_withdraw_bank_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='쿠폰명')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='쿠폰 설명')),
                ('price', models.PositiveIntegerField(help_text='100이하로 지정하는 경우 할인율(%)로 적용됩니다.', verbose_name='가액')),
                ('amount_condition', models.PositiveIntegerField(blank=True, default=0, help_text='정액 쿠폰일 경우 사용가능 미션 최저금액, 정률 쿠폰일 경우 할인 최대금액', verbose_name='금액 제한조건')),
                ('user_register_code', models.CharField(blank=True, default='', help_text='유져가 직접 등록할 쿠폰인 경우에만 값을 입력해주세요.', max_length=6, verbose_name='유져 등록 코드')),
                ('active_days', models.PositiveSmallIntegerField(default=30, verbose_name='유효기간일수')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '쿠폰 템플릿',
                'verbose_name_plural': '쿠폰 템플릿',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_date', models.DateField(verbose_name='유효기한')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='발급일시')),
                ('used_datetime', models.DateTimeField(blank=True, null=True, verbose_name='사용일시')),
                ('issued_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_coupons', to=settings.AUTH_USER_MODEL, verbose_name='발급한 회원')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='payment.CouponTemplate', verbose_name='쿠폰')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='발급받은 회원')),
            ],
            options={
                'verbose_name': '쿠폰',
                'verbose_name_plural': '쿠폰',
            },
        ),
    ]
