# Generated by Django 2.2.7 on 2021-04-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0026_coupon_coupontemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='유효기한'),
        ),
    ]
