# Generated by Django 2.2.7 on 2021-04-21 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0027_auto_20210421_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='issued_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_coupons', to=settings.AUTH_USER_MODEL, verbose_name='발급한 회원'),
        ),
    ]
