# Generated by Django 2.2.7 on 2021-04-22 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0028_auto_20210421_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='payment.Coupon', verbose_name='쿠폰 사용'),
        ),
    ]
