# Generated by Django 2.2.7 on 2021-05-04 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0030_coupon_tasker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='payment.Coupon', verbose_name='쿠폰 사용'),
        ),
    ]
