# Generated by Django 2.2.7 on 2021-07-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0031_auto_20210504_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='added_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '시스템'), (1, '계정간 이전'), (5, '고객 보상'), (9, '임직원 포인트 충전'), (11, '비대면바우처 충전 (+부가세)'), (12, '비대면바우처 충전 (부가세 충전 제외)')], default=0, verbose_name='추가유형'),
        ),
    ]
