# Generated by Django 2.2.7 on 2020-02-10 02:26

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_method', models.CharField(choices=[('push', 'Push'), ('sms', 'SMS'), ('email', 'Email')], max_length=5, verbose_name='메세지 타입')),
                ('receiver_identifier', models.CharField(blank=True, default='', max_length=200, verbose_name='수신 식별자')),
                ('subject', models.CharField(blank=True, default='', max_length=100, verbose_name='제목')),
                ('content', models.TextField(blank=True, default='', verbose_name='내용')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('requested_datetime', models.DateTimeField(blank=True, null=True, verbose_name='발송요청일시')),
                ('retried_datetime', models.DateTimeField(blank=True, null=True, verbose_name='재시도일시')),
                ('done_datetime', models.DateTimeField(blank=True, null=True, verbose_name='발송완료일시')),
                ('failed_datetime', models.DateTimeField(blank=True, null=True, verbose_name='발송실패일시')),
                ('read_datetime', models.DateTimeField(blank=True, null=True, verbose_name='수신일시')),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='결과')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='작성회원')),
                ('receiver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='수신회원')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림',
            },
        ),
    ]
