# Generated by Django 2.2.7 on 2020-02-14 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receiver_user',
            field=models.ForeignKey(blank=True, help_text='회원이 선택된 경우 수신 식별자보다 우선 적용됩니다.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='수신회원'),
        ),
    ]
