# Generated by Django 2.2.7 on 2020-02-26 05:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20200214_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='데이터'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='send_method',
            field=models.CharField(choices=[('push', 'Push'), ('sms', 'SMS')], max_length=5, verbose_name='메세지 타입'),
        ),
    ]
