# Generated by Django 2.2.7 on 2020-02-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_popup'),
        ('notification', '0003_auto_20200226_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='receiver_areas',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='base.Area', verbose_name='수신 지역'),
        ),
    ]
