# Generated by Django 2.2.7 on 2021-02-25 19:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_auto_20200313_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='제목')),
                ('code', models.SlugField(max_length=10, unique=True, verbose_name='슬러그')),
                ('query', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='쿼리')),
            ],
            options={
                'verbose_name': '수신그룹',
                'verbose_name_plural': '수신그룹',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='receiver_tags',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='notification.ReceiverGroup', verbose_name='수신그룹'),
        ),
    ]
