# Generated by Django 2.2.7 on 2021-02-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_auto_20210225_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='receiver_tags',
            new_name='receiver_groups',
        ),
    ]
