# Generated by Django 2.2.7 on 2021-03-04 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_notificationlog_is_requested'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationLog',
        ),
    ]
