# Generated by Django 2.2.7 on 2021-03-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0011_delete_notificationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='data',
        ),
        migrations.AddField(
            model_name='notification',
            name='data_obj_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='랜딩 오브젝트 ID'),
        ),
        migrations.AddField(
            model_name='notification',
            name='data_page',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='랜딩 페이지'),
        ),
        migrations.AddField(
            model_name='notification',
            name='data_type',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='랜딩 타입'),
        ),
    ]
