# Generated by Django 2.2.7 on 2021-03-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_auto_20210304_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivergroup',
            name='code',
            field=models.SlugField(max_length=20, unique=True, verbose_name='슬러그'),
        ),
    ]
