# Generated by Django 2.2.7 on 2021-04-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0014_marketingtasker'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingtasker',
            name='title',
            field=models.TextField(default='제목', verbose_name='메세지 제목'),
            preserve_default=False,
        ),
    ]
