# Generated by Django 2.2.7 on 2021-04-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0015_marketingtasker_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketingtasker',
            options={'verbose_name': '마케팅 태스커', 'verbose_name_plural': '마케팅 태스커'},
        ),
        migrations.AlterField(
            model_name='marketingtasker',
            name='content',
            field=models.TextField(help_text='다음 항목을 사용할 수 있습니다: {code}, {mobile}, {email}, {username}, {state}', verbose_name='메세지 내용'),
        ),
        migrations.AlterField(
            model_name='marketingtasker',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='활성화'),
        ),
        migrations.AlterField(
            model_name='marketingtasker',
            name='title',
            field=models.CharField(max_length=100, verbose_name='메세지 제목'),
        ),
    ]
