# Generated by Django 2.2.7 on 2021-04-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0016_auto_20210423_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingtasker',
            name='content',
        ),
        migrations.RemoveField(
            model_name='marketingtasker',
            name='send_method',
        ),
        migrations.RemoveField(
            model_name='marketingtasker',
            name='title',
        ),
        migrations.AddField(
            model_name='marketingtasker',
            name='email_content',
            field=models.TextField(default='', help_text='다음 항목을 사용할 수 있습니다: {code}, {mobile}, {email}, {username}, {state}', verbose_name='이메일 내용'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketingtasker',
            name='email_title',
            field=models.CharField(default='', help_text='다음 항목을 사용할 수 있습니다: {code}, {mobile}, {email}, {username}, {state}', max_length=100, verbose_name='이메일 제목'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketingtasker',
            name='push_content',
            field=models.TextField(default='', help_text='다음 항목을 사용할 수 있습니다: {code}, {mobile}, {email}, {username}, {state}', verbose_name='푸시 내용'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketingtasker',
            name='push_title',
            field=models.CharField(default='', help_text='다음 항목을 사용할 수 있습니다: {code}, {mobile}, {email}, {username}, {state}', max_length=100, verbose_name='푸시 제목'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketingtasker',
            name='sms_content',
            field=models.TextField(default='', help_text='다음 항목을 사용할 수 있습니다: {code}, {mobile}, {email}, {username}, {state}', verbose_name='SMS 내용'),
            preserve_default=False,
        ),
    ]
