# Generated by Django 2.2.7 on 2021-04-23 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0018_auto_20210423_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tasker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notification.MarketingTasker', verbose_name='태스커'),
        ),
    ]
