# Generated by Django 2.2.7 on 2021-04-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0019_notification_tasker'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingtasker',
            name='is_lazy',
            field=models.BooleanField(blank=True, default=False, verbose_name='lazy process'),
        ),
    ]
