# Generated by Django 2.2.7 on 2021-04-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0020_marketingtasker_is_lazy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingtasker',
            name='condition',
            field=models.CharField(choices=[('joined', '회원가입 즉시'), ('joined_remind_72', '회원가입 후 72시간동안 미션 없음'), ('first_mission_done', '첫 미션 완료'), ('timeout_canceled', '미션 시간초과 취소')], max_length=100, verbose_name='조건'),
        ),
    ]
