# Generated by Django 2.2.7 on 2021-05-21 17:19

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0023_auto_20210520_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingtasker',
            name='active_term',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True, verbose_name='활성화 기간'),
        ),
    ]
