# Generated by Django 2.2.7 on 2021-05-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0024_marketingtasker_active_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingtasker',
            name='active_term',
        ),
        migrations.AddField(
            model_name='marketingtasker',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='활성화 종료일'),
        ),
        migrations.AddField(
            model_name='marketingtasker',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='활성화 시작일'),
        ),
    ]
