# Generated by Django 2.2.7 on 2021-05-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0025_auto_20210521_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingtasker',
            name='condition',
            field=models.CharField(choices=[('joined', '회원가입 즉시'), ('joined_remind_72', '회원가입 후 72시간동안 미션 없음'), ('first_mission_done', '첫 미션 완료'), ('coupon_expire_remind_5d', '쿠폰 만료 5일전'), ('coupon_expire_remind_10d', '쿠폰 만료 10일전'), ('2nd_mission_done_in_peoriod', '기간내에 미션 2회 완료')], max_length=100, verbose_name='조건'),
        ),
    ]
