# Generated by Django 2.2.7 on 2021-06-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0027_auto_20210608_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='send_method',
            field=models.CharField(choices=[('push', 'Push'), ('sms', 'SMS'), ('email', 'Email'), ('kakao', '카카오')], max_length=5, verbose_name='메세지 타입'),
        ),
    ]
