# Generated by Django 2.2.7 on 2021-07-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0032_point_added_type'),
        ('notification', '0028_auto_20210608_1832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarketingTasker',
            new_name='Tasker',
        ),
        migrations.AlterModelOptions(
            name='tasker',
            options={'verbose_name': '알림 태스커', 'verbose_name_plural': '알림 태스커'},
        ),
    ]
