# Generated by Django 2.2.7 on 2019-12-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191211_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='고객 등급'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='헬퍼 등급'),
        ),
    ]
