# Generated by Django 2.2.7 on 2019-12-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191218_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regular',
            name='name',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='이름'),
        ),
    ]
