# Generated by Django 2.2.7 on 2019-12-20 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_bannedword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': '퀴즈', 'verbose_name_plural': '퀴즈'},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answers',
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='답안')),
                ('is_correct', models.BooleanField(blank=True, default=False, verbose_name='정답')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='accounts.Quiz', verbose_name='문제')),
            ],
            options={
                'verbose_name': '답안',
                'verbose_name_plural': '답안',
            },
        ),
    ]
