# Generated by Django 2.2.7 on 2019-12-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191220_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='code',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_code',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'KDB산업은행'), (3, 'IBK기업은행'), (4, '국민은행'), (5, '외환은행'), (7, '수협중앙회'), (11, '농협(중앙회)'), (12, '농협(단위농협)'), (20, '우리은행'), (23, 'SC제일은행'), (27, '한국씨티은행'), (31, '대구은행'), (32, '부산은행'), (34, '광주은행'), (35, '제주은행'), (37, '전북은행'), (39, '경남은행'), (81, 'KEB하나은행'), (88, '신한은행'), (45, '새마을금고'), (48, '신협중앙회'), (50, '상호저축은행'), (54, 'HSBC은행'), (55, '도이치은행'), (89, '케이뱅크'), (90, '카카오뱅크')], null=True, verbose_name='은행'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='예금주'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='계좌번호'),
        ),
    ]
