# Generated by Django 2.2.7 on 2019-12-24 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20191223_0958'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='nearby',
        ),
        migrations.RemoveField(
            model_name='area',
            name='parent',
        ),
        migrations.DeleteModel(
            name='BannedWord',
        ),
        migrations.AlterField(
            model_name='helper',
            name='accept_area',
            field=models.ManyToManyField(related_name='helpers', to='base.Area', verbose_name='수행지역'),
        ),
        migrations.AlterField(
            model_name='regular',
            name='address_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_helpers', to='base.Area', verbose_name='주소 지역'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
