# Generated by Django 2.2.7 on 2019-12-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20191226_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regular',
            name='address_detail',
        ),
        migrations.AddField(
            model_name='regular',
            name='address_detail_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='주소 상세 1'),
        ),
        migrations.AddField(
            model_name='regular',
            name='address_detail_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='주소 상세 2'),
        ),
    ]
