# Generated by Django 2.2.7 on 2019-12-27 07:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_popup'),
        ('accounts', '0012_auto_20191227_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helper',
            name='is_regular',
        ),
        migrations.AddField(
            model_name='helper',
            name='accepted_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='승인일시'),
        ),
        migrations.AddField(
            model_name='helper',
            name='address_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_helpers', to='base.Area', verbose_name='주소 지역'),
        ),
        migrations.AddField(
            model_name='helper',
            name='address_detail_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='주소 상세 1'),
        ),
        migrations.AddField(
            model_name='helper',
            name='address_detail_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='주소 상세 2'),
        ),
        migrations.AddField(
            model_name='helper',
            name='id_person_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='신분증과 함께 찍은 사진'),
        ),
        migrations.AddField(
            model_name='helper',
            name='id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='신분증 사진'),
        ),
        migrations.AddField(
            model_name='helper',
            name='name',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='helper',
            name='rejected_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='거부일시'),
        ),
        migrations.AddField(
            model_name='helper',
            name='rejected_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None, verbose_name='거부 필드'),
        ),
        migrations.AddField(
            model_name='helper',
            name='rejected_reason',
            field=models.TextField(blank=True, verbose_name='거부 이유'),
        ),
        migrations.DeleteModel(
            name='Regular',
        ),
    ]
