# Generated by Django 2.2.7 on 2019-12-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20191227_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='accept_area',
            field=models.ManyToManyField(blank=True, related_name='helpers', to='base.Area', verbose_name='수행지역'),
        ),
    ]
