# Generated by Django 2.2.7 on 2020-01-03 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20191227_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizanswer',
            options={'ordering': ('id',), 'verbose_name': '답안', 'verbose_name_plural': '답안'},
        ),
    ]
