# Generated by Django 2.2.7 on 2020-01-17 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200103_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceblock',
            name='reason',
        ),
    ]
