# Generated by Django 2.2.7 on 2020-02-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_serviceblock_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(db_index=True, max_length=5, unique=True, verbose_name='회원코드'),
        ),
    ]
