# Generated by Django 2.2.7 on 2020-02-24 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200218_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='TIN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BinaryField(verbose_name='번호')),
                ('helper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tin', to='accounts.Helper', verbose_name='헬퍼')),
            ],
            options={
                'verbose_name': '주민번호',
                'verbose_name_plural': '주민번호',
            },
        ),
    ]
