# Generated by Django 2.2.7 on 2020-03-16 11:51

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200312_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedInDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_token', models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='Push 토큰')),
                ('push_ringtone', models.CharField(blank=True, default='', max_length=20, verbose_name='푸시 알림음')),
                ('device_info', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='기기 정보')),
                ('app_info', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='앱 정보')),
                ('logged_in_datetime', models.DateTimeField(auto_now_add=True, verbose_name='로그인 일시')),
                ('logged_out_datetime', models.DateTimeField(blank=True, null=True, verbose_name='로그아웃 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_devices', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '로그인 기기',
                'verbose_name_plural': '로그인 기기',
            },
        ),
    ]
