# Generated by Django 2.2.7 on 2020-04-16 11:08

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_mobilephone_is_logged_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default='', max_length=11, validators=[django.core.validators.RegexValidator('^01([0|1|6|7|8|9]?)([0-9]{3,4})([0-9]{4})$')], verbose_name='휴대폰 번호')),
                ('code', models.CharField(max_length=6, verbose_name='인증코드')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('verified_datetime', models.DateTimeField(blank=True, null=True, verbose_name='휴대폰 인증 일시')),
            ],
            options={
                'verbose_name': '휴대폰 인증',
                'verbose_name_plural': '휴대폰 인증',
            },
        ),
        migrations.CreateModel(
            name='ServiceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='서비스 이름')),
            ],
        ),
        migrations.RemoveField(
            model_name='mobilephoneverification',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='helper',
            name='details',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kakao_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='naver_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='push_ringtone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='push_token',
        ),
        migrations.AddField(
            model_name='helper',
            name='best_moment',
            field=models.TextField(blank=True, null=True, verbose_name='행복했던 순간'),
        ),
        migrations.AddField(
            model_name='helper',
            name='experience',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='경력'),
        ),
        migrations.AddField(
            model_name='helper',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='활성헬퍼여부'),
        ),
        migrations.AddField(
            model_name='helper',
            name='is_profile_public',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='프로필 사진 공개여부'),
        ),
        migrations.AddField(
            model_name='helper',
            name='means_of_transport',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None, verbose_name='이동수단'),
        ),
        migrations.AddField(
            model_name='helper',
            name='usable_tools',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None, verbose_name='보유장비'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='휴대폰 번호'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='자기소개'),
        ),
        migrations.RemoveField(
            model_name='helper',
            name='services',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, unique=True, verbose_name='이메일'),
        ),
        migrations.DeleteModel(
            name='MobilePhone',
        ),
        migrations.DeleteModel(
            name='MobilePhoneVerification',
        ),
        migrations.AddField(
            model_name='mobileverification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
        migrations.AddField(
            model_name='helper',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='helpers', to='accounts.ServiceTag', verbose_name='제공 서비스'),
        ),
    ]
