# Generated by Django 2.2.7 on 2020-04-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20200416_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.NullBooleanField(choices=[(False, '남자'), (True, '여자'), (None, '- 선택 안함 -')], verbose_name='성별'),
        ),
    ]
