# Generated by Django 2.2.7 on 2020-04-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20200416_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='_job',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='직업'),
        ),
        migrations.AddField(
            model_name='helper',
            name='_joined_from',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='가입경로'),
        ),
        migrations.AddField(
            model_name='user',
            name='_auth_center',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='인증센터'),
        ),
        migrations.AddField(
            model_name='user',
            name='_recommended_by',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='추천인 코드'),
        ),
    ]
