# Generated by Django 2.2.7 on 2020-04-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20200416_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_auth_center',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='인증센터'),
        ),
    ]
