# Generated by Django 2.2.7 on 2020-04-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_helper_is_online_acceptable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helper',
            old_name='push_not_allowed_from',
            new_name='push_allowed_from',
        ),
        migrations.RenameField(
            model_name='helper',
            old_name='push_not_allowed_to',
            new_name='push_allowed_to',
        ),
        migrations.AddField(
            model_name='helper',
            name='is_mission_request_push_allowed',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='미션요청 푸시 허용'),
        ),
    ]
