# Generated by Django 2.2.7 on 2020-04-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20200424_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='push_allowed_from',
            field=models.TimeField(blank=True, null=True, verbose_name='알림허용 시작'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='push_allowed_to',
            field=models.TimeField(blank=True, null=True, verbose_name='알림허용 종료'),
        ),
    ]
