# Generated by Django 2.2.7 on 2020-04-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20200424_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetag',
            options={'verbose_name': '제공서비스 태그', 'verbose_name_plural': '제공서비스 태그'},
        ),
    ]
