# Generated by Django 2.2.7 on 2020-06-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_user_recommended_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='상태코드')),
                ('state_type', models.CharField(max_length=10, verbose_name='상태타입')),
                ('name', models.CharField(max_length=20, verbose_name='상태 표시명')),
            ],
            options={
                'verbose_name': '상태',
                'verbose_name_plural': '상태',
            },
        ),
    ]
