# Generated by Django 2.2.7 on 2020-06-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state_type',
            field=models.CharField(choices=[('user', '회원'), ('mission', '미션')], max_length=10, verbose_name='상태타입'),
        ),
    ]
