# Generated by Django 2.2.7 on 2020-07-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20200619_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='_additional_mission_canceled_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='추가 미션 취소건수'),
        ),
        migrations.AddField(
            model_name='helper',
            name='_additional_mission_done_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='추가 미션 수행건수'),
        ),
    ]
