# Generated by Django 2.2.7 on 2020-07-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20200713_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='계좌번호'),
        ),
    ]
