# Generated by Django 2.2.7 on 2020-08-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_helper_profile_photo_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='is_profile_photo_accepted',
            field=models.NullBooleanField(default=None, verbose_name='프로필 변경 승인여부'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='profile_photo_applied',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='신청중인 프로필 사진'),
        ),
    ]
