# Generated by Django 2.2.7 on 2020-08-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20200818_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='is_profile_photo_accepted',
            field=models.NullBooleanField(default=True, verbose_name='프로필 변경 승인여부'),
        ),
    ]
