# Generated by Django 2.2.7 on 2020-11-16 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_serviceblock_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='협력사명')),
                ('code', models.CharField(db_index=True, max_length=5, unique=True, verbose_name='협력사코드')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managing_partnership', to=settings.AUTH_USER_MODEL, verbose_name='대표 아이디')),
            ],
            options={
                'verbose_name': '협력사',
                'verbose_name_plural': '협력사',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='partnership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.Partnership', verbose_name='협력사 계정'),
        ),
    ]
