# Generated by Django 2.2.7 on 2020-12-07 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20201116_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='partnership',
        ),
        migrations.AddField(
            model_name='user',
            name='recommended_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_users', to='accounts.Partnership', verbose_name='추천 협력사'),
        ),
    ]
