# Generated by Django 2.2.7 on 2020-12-11 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20201208_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recommended_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended', to=settings.AUTH_USER_MODEL, verbose_name='추천인'),
        ),
    ]
