# Generated by Django 2.2.7 on 2020-12-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20201211_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_legacy_recommended',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='구버젼 추천인 코드'),
        ),
    ]
