# Generated by Django 2.2.7 on 2021-01-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_user__legacy_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ad_allowed',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='마케팅 정보 허용'),
        ),
    ]
