# Generated by Django 2.2.7 on 2021-05-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_auto_20210507_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='has_pet',
            field=models.BooleanField(blank=True, default=False, verbose_name='펫 여부'),
        ),
    ]
