# Generated by Django 2.2.7 on 2021-05-26 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_auto_20210525_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helper',
            name='has_pet',
        ),
    ]
