# Generated by Django 2.2.7 on 2021-05-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_remove_helper_has_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='has_pet',
            field=models.NullBooleanField(verbose_name='펫 여부'),
        ),
    ]
