# Generated by Django 2.2.7 on 2021-06-09 14:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_helper_has_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='usable_tools',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='보유장비'),
        ),
    ]
