# Generated by Django 2.2.7 on 2021-07-07 17:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_auto_20210609_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileverification',
            name='nice_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='나이스 본인인증 정보'),
        ),
    ]
