# Generated by Django 2.2.7 on 2021-07-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_mobileverification_nice_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ci',
            field=models.CharField(blank=True, default='', max_length=90, verbose_name='CI'),
        ),
    ]
