# Generated by Django 2.2.7 on 2022-03-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_auto_20211005_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='이름'),
        ),
    ]
