# Generated by Django 2.2.7 on 2022-03-17 14:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_auto_20220317_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='experience',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, size=None, verbose_name='경력'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='licenses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, size=None, verbose_name='자격증'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='usable_tools',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, size=None, verbose_name='보유장비'),
        ),
        migrations.AlterField(
            model_name='servicetag',
            name='title',
            field=models.CharField(max_length=250, verbose_name='서비스 이름'),
        ),
    ]
