# Generated by Django 2.2.7 on 2022-05-23 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_auto_20220317_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='수수료율')),
                ('start_date', models.DateField(verbose_name='적용 시작일시')),
                ('end_date', models.DateField(verbose_name='적용 종료일시')),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_rates', to='accounts.Helper', verbose_name='헬퍼')),
            ],
            options={
                'verbose_name': '기간 수수료율',
                'verbose_name_plural': '기간 수수료율',
            },
        ),
    ]
