# Generated by Django 2.2.7 on 2022-05-23 03:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_feerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='feerate',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='등록일시'),
            preserve_default=False,
        ),
    ]
