# Generated by Django 2.2.7 on 2019-12-31 00:20

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_popup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0014_auto_20191227_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_1', models.CharField(max_length=100, verbose_name='상세 주소')),
                ('detail_2', models.CharField(blank=True, default='', max_length=100, verbose_name='상세 주소')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Area', verbose_name='지역')),
            ],
            options={
                'verbose_name': '미션용 주소',
                'verbose_name_plural': '미션용 주소',
            },
        ),
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final', to='missions.Address', verbose_name='최종 목적지')),
                ('stopovers', models.ManyToManyField(blank=True, related_name='stopovers', to='missions.Address', verbose_name='경유지')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_books', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '미션 주소록',
                'verbose_name_plural': '미션 주소록',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0, verbose_name='입찰가')),
                ('is_assigned', models.BooleanField(blank=True, default=False, verbose_name='지정 미션 여부')),
                ('applied_datetime', models.DateTimeField(blank=True, null=True, verbose_name='입찰일시')),
                ('won_datetime', models.DateTimeField(blank=True, null=True, verbose_name='낙찰일시')),
                ('_due_datetime', models.DateTimeField(blank=True, null=True, verbose_name='미션 일시')),
                ('_canceled_datetime', models.DateTimeField(blank=True, null=True, verbose_name='취소일시')),
                ('_done_datetime', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='accounts.Helper', verbose_name='헬퍼')),
            ],
            options={
                'verbose_name': '미션 입찰',
                'verbose_name_plural': '미션 입찰',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('due_datetime', models.DateTimeField(blank=True, null=True, verbose_name='미션 일시')),
                ('is_due_modifiable', models.BooleanField(blank=True, default=False, verbose_name='미션일시 수정가능')),
                ('product', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='제품 정보')),
                ('amount_high', models.IntegerField(default=0, null=True, verbose_name='최고가')),
                ('amount_low', models.IntegerField(default=0, null=True, verbose_name='최저가')),
                ('charge_rate', models.SmallIntegerField(blank=True, default=10, verbose_name='수수료율')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='작성 일시')),
                ('requested_datetime', models.DateTimeField(blank=True, null=True, verbose_name='요청 일시')),
                ('canceled_datetime', models.DateTimeField(blank=True, null=True, verbose_name='취소일시')),
                ('address_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='missions.AddressBook', verbose_name='미션 주소록')),
            ],
            options={
                'verbose_name': '미션',
                'verbose_name_plural': '미션',
            },
        ),
        migrations.CreateModel(
            name='MissionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='타입명')),
                ('description', models.CharField(max_length=250, verbose_name='타입 설명')),
                ('product_fields', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='상품 필드')),
            ],
            options={
                'verbose_name': '미션 타입',
                'verbose_name_plural': '미션 타입',
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='차단 일시')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('related_mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_blocks', to='missions.Mission', verbose_name='미션')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_bys', to=settings.AUTH_USER_MODEL, verbose_name='차단된 회원')),
            ],
            options={
                'verbose_name': '사용자 차단',
                'verbose_name_plural': '사용자 차단',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.SmallIntegerField(choices=[(1, '')], verbose_name='신고 분류')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='작성 일시')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='missions.Bid', verbose_name='입찰')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '신고',
                'verbose_name_plural': '신고',
            },
        ),
        migrations.CreateModel(
            name='PenaltyPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.SmallIntegerField(choices=[(1, '욕설, 비난, 혐오성 발언'), (2, '개인적 연락 (만남시도)'), (3, '개인거래 유도'), (4, '추가비용 요구 (허위입찰)'), (5, '잠수 / No Show'), (6, '불성실 미션수행'), (7, '고객센터에 욕설, 비난, 혐오, 비방성 발언'), (8, '홍보, 광고용으로 사용'), (9, '불법/위험 미션 요청'), (99, '기타')], verbose_name='사유')),
                ('point', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(-8), django.core.validators.MaxValueValidator(8)], verbose_name='점수')),
                ('detail', models.TextField(verbose_name='상세 사유')),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='penalty', to='missions.Mission', verbose_name='관련 미션')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_points', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '벌점',
                'verbose_name_plural': '벌점',
            },
        ),
        migrations.CreateModel(
            name='MissionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach', models.FileField(upload_to='', verbose_name='파일')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='missions.Mission', verbose_name='미션')),
            ],
            options={
                'verbose_name': '미션 수행 관련 파일',
                'verbose_name_plural': '미션 수행 관련 파일',
            },
        ),
        migrations.AddField(
            model_name='mission',
            name='mission_type',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='missions.MissionType', verbose_name='미션 타입'),
        ),
        migrations.AddField(
            model_name='mission',
            name='request_areas',
            field=models.ManyToManyField(blank=True, to='base.Area', verbose_name='요청 지역'),
        ),
        migrations.AddField(
            model_name='mission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.PositiveSmallIntegerField(choices=[(1, '취소'), (5, '일시변경'), (9, '완료')], verbose_name='미션 인터랙션')),
                ('detail', models.TextField(blank=True, verbose_name='상세 내용')),
                ('requested_datetime', models.DateTimeField(auto_now_add=True, verbose_name='요청 일시')),
                ('accepted_datetime', models.DateTimeField(blank=True, null=True, verbose_name='수락 일시')),
                ('canceled_datetime', models.DateTimeField(blank=True, null=True, verbose_name='취소 일시')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='missions.Bid', verbose_name='입찰')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '미션 인터랙션',
                'verbose_name_plural': '미션 인터랙션',
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='missions.Mission', verbose_name='미션'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]), size=2, verbose_name='별점')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='작성 일시')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='missions.Bid', verbose_name='입찰')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reviews', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰',
                'unique_together': {('bid', 'created_user')},
            },
        ),
    ]
