# Generated by Django 2.2.7 on 2020-01-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_auto_20191231_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='is_point_reward',
            field=models.BooleanField(blank=True, default=False, verbose_name='포인트 보상'),
        ),
    ]
