# Generated by Django 2.2.7 on 2020-01-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_mission_is_point_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='bid_closed_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='입찰종료일시'),
        ),
    ]
