# Generated by Django 2.2.7 on 2020-01-13 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_mission_bid_closed_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='category',
        ),
    ]
