# Generated by Django 2.2.7 on 2020-01-13 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0006_remove_report_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='penaltypoint',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='부여 일시'),
            preserve_default=False,
        ),
    ]
