# Generated by Django 2.2.7 on 2020-01-13 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0007_penaltypoint_created_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblock',
            name='related_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_blocks', to='missions.Mission', verbose_name='미션'),
        ),
    ]
