# Generated by Django 2.2.7 on 2020-01-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0008_auto_20200113_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='is_due_modifiable',
        ),
        migrations.AddField(
            model_name='mission',
            name='is_due_date_modifiable',
            field=models.BooleanField(blank=True, default=False, verbose_name='미션일자 수정가능'),
        ),
        migrations.AddField(
            model_name='mission',
            name='is_due_time_modifiable',
            field=models.BooleanField(blank=True, default=False, verbose_name='미션시간 수정가능'),
        ),
    ]
