# Generated by Django 2.2.7 on 2020-01-21 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0009_auto_20200117_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penaltypoint',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_points', to='missions.Mission', verbose_name='관련 미션'),
        ),
    ]
