# Generated by Django 2.2.7 on 2020-01-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0012_auto_20200128_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='missiontype',
            name='bidding_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='입찰 제한시간 (분)'),
        ),
    ]
