# Generated by Django 2.2.7 on 2020-02-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0015_auto_20200204_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='adjusted_due_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='적용 미션 일시'),
        ),
    ]
