# Generated by Django 2.2.7 on 2020-02-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0016_auto_20200204_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='missiontype',
            name='charge_rate',
            field=models.SmallIntegerField(blank=True, default=10, verbose_name='수수료율'),
        ),
    ]
