# Generated by Django 2.2.7 on 2020-02-14 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('missions', '0017_missiontype_charge_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='cash',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bid', to='payment.Cash', verbose_name='캐쉬'),
        ),
    ]
