# Generated by Django 2.2.7 on 2020-02-14 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0018_bid_cash'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionWarningNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='안내 문구')),
            ],
            options={
                'verbose_name': '위험미션 키워드',
                'verbose_name_plural': '위험미션 키워드',
            },
        ),
        migrations.CreateModel(
            name='DangerousKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20, verbose_name='키워드')),
                ('warning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='missions.MissionWarningNotice')),
            ],
            options={
                'verbose_name': '경고 키워드',
                'verbose_name_plural': '경고 키워드',
            },
        ),
        migrations.AddField(
            model_name='mission',
            name='warning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='missions.MissionWarningNotice'),
        ),
    ]
