# Generated by Django 2.2.7 on 2020-02-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0020_interaction_rejected_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='rejected_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='거절 일시'),
        ),
    ]
