# Generated by Django 2.2.7 on 2020-02-20 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0022_auto_20200218_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penaltypoint',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalty_points', to='missions.Mission', verbose_name='관련 미션'),
        ),
    ]
