# Generated by Django 2.2.7 on 2020-02-21 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0023_auto_20200220_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='warning',
        ),
    ]
