# Generated by Django 2.2.7 on 2020-02-25 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missions', '0027_customerservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservice',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cs', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
