# Generated by Django 2.2.7 on 2020-02-25 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0028_customerservice_created_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservice',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='상담 일시'),
            preserve_default=False,
        ),
    ]
