# Generated by Django 2.2.7 on 2020-03-03 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_reward'),
        ('missions', '0029_customerservice_created_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='point',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bid', to='payment.Point', verbose_name='포인트'),
        ),
        migrations.AddField(
            model_name='bid',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='payment.Reward', verbose_name='리워드'),
        ),
        migrations.AddField(
            model_name='review',
            name='cash',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review', to='payment.Cash', verbose_name='캐쉬'),
        ),
        migrations.AddField(
            model_name='review',
            name='point',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review', to='payment.Point', verbose_name='포인트'),
        ),
        migrations.AddField(
            model_name='review',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='payment.Reward', verbose_name='리워드'),
        ),
    ]
