# Generated by Django 2.2.7 on 2020-03-03 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missions', '0030_auto_20200303_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach', models.FileField(upload_to='', verbose_name='파일')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='missions.Bid', verbose_name='입찰')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_files', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '미션 수행중 애니톡 교환 파일',
                'verbose_name_plural': '미션 수행중 애니톡 교환 파일',
            },
        ),
    ]
