# Generated by Django 2.2.7 on 2020-03-07 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0032_auto_20200305_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='mission_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='missions.MissionType', verbose_name='미션 타입'),
        ),
        migrations.AlterField(
            model_name='multiareamission',
            name='customer_mobile',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='고객 연락처'),
        ),
        migrations.AlterField(
            model_name='multimission',
            name='mission_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='multi_missions', to='missions.MissionType', verbose_name='미션 타입'),
        ),
        migrations.AlterField(
            model_name='multimission',
            name='request_helpers',
            field=models.ManyToManyField(blank=True, help_text='요청 헬퍼를 지정하는 경우, 해당 헬퍼에게만 노출됩니다.', to='accounts.Helper', verbose_name='요청 헬퍼'),
        ),
    ]
