# Generated by Django 2.2.7 on 2020-03-31 16:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0035_auto_20200325_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryIkeaMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='제품')),
                ('items_quantity', models.PositiveSmallIntegerField(verbose_name='제품수')),
                ('expected_min_cost', models.PositiveIntegerField(verbose_name='예상최소금액')),
                ('expected_max_cost', models.PositiveIntegerField(verbose_name='예상최대금액')),
                ('address', models.CharField(blank=True, default='', max_length=250, verbose_name='주소')),
                ('address_detail', models.CharField(blank=True, default='', max_length=100, verbose_name='주소 상세')),
                ('request', models.TextField(blank=True, default='', verbose_name='요청사항')),
                ('due_datetime', models.DateTimeField(blank=True, null=True, verbose_name='요청일시')),
                ('mobile', models.CharField(blank=True, default='', max_length=15, verbose_name='휴대폰')),
            ],
            options={
                'verbose_name': '임시 이케아 미션요청',
                'verbose_name_plural': '임시 이케아 미션요청',
            },
        ),
    ]
