# Generated by Django 2.2.7 on 2020-04-10 10:32

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missions', '0036_temporaryikeamission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='요청내용')),
                ('mission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='externals', to='missions.Mission', verbose_name='미션')),
            ],
            options={
                'verbose_name': '외부 미션요청',
                'verbose_name_plural': '외부 미션요청',
            },
        ),
        migrations.CreateModel(
            name='ExternalMissionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100, verbose_name='제품 식별자')),
                ('items', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='제품정보')),
            ],
            options={
                'verbose_name': '외부 미션요청 제품',
                'verbose_name_plural': '외부 미션요청 제품',
            },
        ),
        migrations.DeleteModel(
            name='TemporaryIkeaMission',
        ),
        migrations.AddField(
            model_name='missiontype',
            name='user_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charged_mission_types', to=settings.AUTH_USER_MODEL, verbose_name='담당자'),
        ),
        migrations.AddField(
            model_name='externalmissionproduct',
            name='mission_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='missions.MissionType', verbose_name='미션 타입'),
        ),
        migrations.AddField(
            model_name='externalmission',
            name='mission_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='externals', to='missions.MissionType', verbose_name='미션 타입'),
        ),
        migrations.AddField(
            model_name='externalmission',
            name='multi_mission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external', to='missions.MultiMission', verbose_name='다중 미션'),
        ),
    ]
