# Generated by Django 2.2.7 on 2020-04-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0037_auto_20200410_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, default='', max_length=13, verbose_name='별칭'),
        ),
    ]
