# Generated by Django 2.2.7 on 2020-04-17 15:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0038_auto_20200410_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalmission',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='작성일시'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalmission',
            name='reference_code',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='참조 미션코드'),
        ),
        migrations.AlterField(
            model_name='externalmission',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='요청내용'),
        ),
    ]
