# Generated by Django 2.2.7 on 2020-04-21 16:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0040_mission_is_at_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='product',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, verbose_name='제품 정보'),
        ),
    ]
