# Generated by Django 2.2.7 on 2020-04-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0041_auto_20200421_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalmissionproduct',
            name='mission_type',
        ),
        migrations.DeleteModel(
            name='ExternalMission',
        ),
        migrations.DeleteModel(
            name='ExternalMissionProduct',
        ),
    ]
