# Generated by Django 2.2.7 on 2020-06-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0045_auto_20200520_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='missiontype',
            name='minimum_amount',
            field=models.SmallIntegerField(blank=True, default=1000, verbose_name='입찰 하한가'),
        ),
    ]
