# Generated by Django 2.2.7 on 2020-06-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0046_missiontype_minimum_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='missiontype',
            name='class_name',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='클래스명'),
        ),
    ]
