# Generated by Django 2.2.7 on 2020-06-19 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20200619_1333'),
        ('missions', '0047_missiontype_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='saved_state',
            field=models.ForeignKey(blank=True, default='not_applied', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bids', to='accounts.State', to_field='code', verbose_name='상태'),
        ),
        migrations.AddField(
            model_name='mission',
            name='saved_state',
            field=models.ForeignKey(blank=True, default='draft', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='missions', to='accounts.State', to_field='code', verbose_name='상태'),
        ),
    ]
