# Generated by Django 2.2.7 on 2020-06-22 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20200619_1333'),
        ('missions', '0048_auto_20200619_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiareamission',
            name='saved_state',
            field=models.ForeignKey(blank=True, default='draft', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='area_missions', to='accounts.State', to_field='code', verbose_name='상태'),
        ),
        migrations.AddField(
            model_name='multimission',
            name='saved_state',
            field=models.ForeignKey(blank=True, default='draft', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='multi_missions', to='accounts.State', to_field='code', verbose_name='상태'),
        ),
    ]
