# Generated by Django 2.2.7 on 2020-07-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0049_auto_20200622_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='_locked_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='잠금일시'),
        ),
    ]
