# Generated by Django 2.2.7 on 2020-07-18 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missions', '0050_bid__locked_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='_is_created_user_helper',
            field=models.NullBooleanField(default=None, verbose_name='작성자 헬퍼여부'),
        ),
        migrations.AddField(
            model_name='review',
            name='_received_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_reviews', to=settings.AUTH_USER_MODEL, verbose_name='수신자'),
        ),
        migrations.AlterField(
            model_name='review',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='missions.Bid', verbose_name='입찰'),
        ),
    ]
