# Generated by Django 2.2.7 on 2020-12-04 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0055_auto_20201013_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='활성화'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='final_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_address_missions', to='missions.Address', verbose_name='최종 목적지'),
        ),
    ]
