# Generated by Django 2.2.7 on 2021-01-11 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0057_missiontemplate_templatecategory_templatequestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missiontemplate',
            name='questions',
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='missions.MissionTemplate', verbose_name='템플릿'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='templatequestion',
            name='question_type',
            field=models.CharField(choices=[('radio', '라디오 (1개 선택)'), ('checkbox', '체크박스 (다중 선택)'), ('number', '숫자 입력'), ('text', '단답형 문자'), ('textarea', '장문'), ('area', '지역'), ('address', '주소'), ('datetime', '날짜와 시간'), ('date', '날짜'), ('time', '시간'), ('customer_mobile', '고객 연락처')], max_length=20, verbose_name='유형'),
        ),
    ]
