# Generated by Django 2.2.7 on 2021-01-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0058_auto_20210111_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatequestion',
            name='order_no',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='순번'),
            preserve_default=False,
        ),
    ]
