# Generated by Django 2.2.7 on 2021-01-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0059_templatequestion_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatequestion',
            name='has_etc_input',
            field=models.BooleanField(blank=True, default=False, verbose_name='직접입력(기타) 추가'),
        ),
        migrations.AlterField(
            model_name='templatequestion',
            name='order_no',
            field=models.PositiveSmallIntegerField(blank=True, default=10, verbose_name='순번'),
        ),
    ]
