# Generated by Django 2.2.7 on 2021-01-19 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0061_auto_20210119_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='missiontemplate',
            name='mission_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='missions.MissionType', verbose_name='미션 타입'),
        ),
    ]
