# Generated by Django 2.2.7 on 2021-01-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0062_missiontemplate_mission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatequestion',
            name='question_type',
            field=models.CharField(choices=[('radio', '라디오 (1개 선택)'), ('checkbox', '체크박스 (다중 선택)'), ('number', '숫자 입력'), ('text', '단답형 문자'), ('textarea', '장문'), ('area', '지역'), ('address', '주소'), ('datetime', '날짜와 시간'), ('date', '날짜'), ('time', '시간'), ('customer_mobile', '고객 연락처'), ('due_datetime', '미션 일시'), ('stopovers', '경유지'), ('final_address', '최종 목적지')], max_length=20, verbose_name='유형'),
        ),
    ]
