# Generated by Django 2.2.7 on 2021-03-16 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0067_auto_20210217_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_services', to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
    ]
