# Generated by Django 2.2.7 on 2021-03-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0068_auto_20210316_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='태그명')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그',
            },
        ),
        migrations.AddField(
            model_name='missiontemplate',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='templates', to='missions.TemplateTag', verbose_name='태그'),
        ),
    ]
