# Generated by Django 2.2.7 on 2021-04-01 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missions', '0069_auto_20210323_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='태그 이미지'),
        ),
        migrations.AddField(
            model_name='templatetag',
            name='weight',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='가중치'),
        ),
        migrations.AlterField(
            model_name='templatetag',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='태그명'),
        ),
        migrations.CreateModel(
            name='TemplateKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='키워드')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='검색일시')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keywords', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '키워드',
                'verbose_name_plural': '키워드',
            },
        ),
    ]
