# Generated by Django 2.2.7 on 2021-04-06 19:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0071_templatekeyword_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetag',
            name='synonyms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=[], size=None, verbose_name='동의어'),
            preserve_default=False,
        ),
    ]
