# Generated by Django 2.2.7 on 2021-04-06 19:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0072_templatetag_synonyms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatetag',
            name='synonyms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, help_text='쉽표로 구분합니다.', size=None, verbose_name='동의어'),
        ),
    ]
