# Generated by Django 2.2.7 on 2021-04-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0073_auto_20210406_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='customer_checked_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='입찰 확인 일시'),
        ),
    ]
