# Generated by Django 2.2.7 on 2021-05-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0074_bid_customer_checked_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='_anytalk_closed_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='애니톡 종료일시'),
        ),
    ]
