# Generated by Django 2.2.7 on 2021-05-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0075_bid__anytalk_closed_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='canceled_detail',
            field=models.TextField(blank=True, verbose_name='취소 상세내용'),
        ),
    ]
