# Generated by Django 2.2.7 on 2021-05-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0076_mission_canceled_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='canceled_detail',
            field=models.TextField(blank=True, default='', verbose_name='취소 상세내용'),
        ),
    ]
