# Generated by Django 2.2.7 on 2021-06-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0077_auto_20210512_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='missiontemplate',
            name='description',
            field=models.TextField(default='', verbose_name='템플릿 설명'),
            preserve_default=False,
        ),
    ]
