# Generated by Django 2.2.7 on 2021-07-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0078_missiontemplate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='bid',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='입찰시 위치 행정동'),
        ),
        migrations.AddField(
            model_name='bid',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='경도'),
        ),
    ]
