# Generated by Django 2.2.7 on 2021-08-27 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_user_ci'),
        ('missions', '0079_auto_20210714_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='missiontemplate',
            name='partnership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Partnership', verbose_name='협력사 전용'),
        ),
        migrations.AlterField(
            model_name='templatequestion',
            name='question_type',
            field=models.CharField(choices=[('radio', '라디오 (1개 선택)'), ('checkbox', '체크박스 (다중 선택)'), ('number', '숫자 입력'), ('text', '단답형 문자'), ('textarea', '장문'), ('area', '지역'), ('address', '주소'), ('datetime', '날짜와 시간'), ('date', '날짜'), ('time', '시간'), ('files', '파일 첨부'), ('due_datetime', '미션 일시'), ('stopovers', '경유지'), ('final_address', '최종 목적지'), ('product', '제품 정보')], max_length=20, verbose_name='유형'),
        ),
    ]
