# Generated by Django 2.2.7 on 2021-09-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0081_auto_20210827_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='missiontemplate',
            name='auto_stopover_address',
            field=models.ForeignKey(blank=True, null=True, on_delete='자동입력 경유지', to='missions.Address'),
        ),
        migrations.AddField(
            model_name='missiontemplate',
            name='content_display',
            field=models.TextField(blank=True, default='', verbose_name='미션내용 표시'),
        ),
    ]
