# Generated by Django 2.2.7 on 2021-09-03 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0082_auto_20210903_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missiontemplate',
            name='auto_stopover_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='missions.Address', verbose_name='자동입력 경유지'),
        ),
    ]
