# Generated by Django 2.2.7 on 2021-09-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0083_auto_20210903_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missiontemplate',
            name='content_display',
            field=models.TextField(blank=True, default='', help_text='질문에 들어가는 항목 이름으로 미션을 자유롭게 표시할 수 있습니다.', verbose_name='미션내용 표시'),
        ),
    ]
