# Generated by Django 2.2.7 on 2021-09-07 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0084_auto_20210903_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missiontemplate',
            name='partnership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='biz.Partnership', verbose_name='협력사 전용'),
        ),
    ]
