# Generated by Django 2.2.7 on 2023-04-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0086_missiontemplate_matching_success_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missiontype',
            name='charge_rate',
            field=models.SmallIntegerField(blank=True, default=16, verbose_name='수수료율'),
        ),
    ]
