# Generated by Django 2.2.7 on 2019-12-24 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannedWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20, verbose_name='단어')),
                ('banned_username', models.BooleanField(blank=True, default=True, verbose_name='회원 닉네임에 적용')),
                ('banned_mission', models.BooleanField(blank=True, default=True, verbose_name='미션 내용에 적용')),
            ],
            options={
                'verbose_name': '금지어',
                'verbose_name_plural': '금지어',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='지역명')),
                ('nearby', models.ManyToManyField(blank=True, related_name='_area_nearby_+', to='base.Area', verbose_name='인근 지역')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base.Area', verbose_name='상위 지역')),
            ],
            options={
                'verbose_name': '지역',
                'verbose_name_plural': '지역',
            },
        ),
    ]
