# Generated by Django 2.2.7 on 2019-12-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('user', '고객 메인'), ('helper', '헬퍼 메인'), ('cs', '고객센터')], max_length=10, verbose_name='위치')),
                ('target_type', models.CharField(choices=[('view', '뷰'), ('post', '게시물'), ('link', '외부링크')], max_length=10, verbose_name='타겟 타입')),
                ('target_id', models.CharField(max_length=100, verbose_name='타겟 식별자')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(blank=True, default='', verbose_name='내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지')),
                ('start_datetime', models.DateTimeField(verbose_name='시작 일시')),
                ('end_datetime', models.DateTimeField(verbose_name='종료 일시')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '팝업',
                'verbose_name_plural': '팝업',
            },
        ),
    ]
