# Generated by Django 2.2.7 on 2020-03-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200325_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='location',
            field=models.CharField(choices=[('user', '고객 메인'), ('helper', '헬퍼 메인'), ('cs', '고객센터')], max_length=15, verbose_name='위치'),
        ),
    ]
