# Generated by Django 2.2.7 on 2021-08-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200325_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popup',
            options={'verbose_name': '팝업 및 배너', 'verbose_name_plural': '팝업 및 배너'},
        ),
    ]
