# Generated by Django 2.2.7 on 2022-03-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210805_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='target_type',
            field=models.CharField(choices=[('view', '뷰'), ('link', '외부링크'), ('webview', '내장 웹뷰'), ('contact', '[게시물] 1:1문의'), ('partnership', '[게시물] 제휴/제안'), ('customer_notice', '[게시물] 공지(고객)'), ('helper_notice', '[게시물] 공지(헬퍼)'), ('customer_event', '[게시물] 이벤트(고객)'), ('helper_event', '[게시물] 이벤트(헬퍼)'), ('magazine', '[게시물] 매거진'), ('webtoon', '[게시물] 웹툰'), ('faq', '[게시물] FAQ')], max_length=15, verbose_name='타겟 타입'),
        ),
    ]
