# Generated by Django 2.2.7 on 2023-04-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220317_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='location',
            field=models.CharField(choices=[('user', '고객 메인'), ('helper', '헬퍼 메인'), ('cs', '고객센터'), ('user_popup', '고객 팝업'), ('helper_popup', '헬퍼 팝업')], max_length=15, verbose_name='위치'),
        ),
    ]
