#!/bin/sh
#
# uwsgi - This script starts and stops the uWSGI emperor
#
# chkconfig:   - 85 15
# description: Fast, self-healing, application container server
# processname: uwsgi

# Source function library.
. /etc/rc.d/init.d/functions

PATH=/usr/bin:/sbin:/bin:/usr/sbin:/usr/local/bin
PROG=/usr/bin/uwsgi
OWNER=uwsgi
NAME=uwsgi
DAEMON_OPTS="--ini /home/anyman/www/web/conf/uwsgi.ini --daemonize /var/log/uwsgi.log"

[ -f /etc/sysconfig/uwsgi ] && . /etc/sysconfig/uwsgi

lockfile=/var/lock/subsys/uwsgi

start () {
    echo -n "Starting $NAME: "
    daemon $PROG $DAEMON_OPTS
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retvalw
}

stop () {
    echo -n "Stopping $NAME: "
    killproc $PROG -INT
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart () {
    stop
    start
}

rh_status () {
    status $PROG
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
  start)
    rh_status_q && exit 0
    $1
    ;;
  stop)
    rh_status_q || exit 0
    $1
    ;;
  restart)
    $1
    ;;
  status)
    rh_status
    ;;
  condrestart|try-restart)
    rh_status_q || exit 0
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|condrestart|try-restart|status}" >&2
    exit 2
    ;;
esac
exit 0