# Generated by Django 2.2.7 on 2020-03-10 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.PositiveSmallIntegerField(choices=[(1, '1:1 문의'), (2, '제휴/제안'), (3, '공지'), (4, '이벤트'), (5, '매거진'), (6, '웹툰'), (7, 'FAQ')], verbose_name='게시판')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('content', django_summernote.fields.SummernoteTextField(blank=True, verbose_name='내용')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_datetime', models.DateTimeField(blank=True, null=True, verbose_name='수정일시')),
                ('viewed_count', models.PositiveIntegerField(blank=True, default=0, verbose_name='조회수')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writings', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글',
            },
        ),
        migrations.CreateModel(
            name='ViewLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('customer', '고객'), ('helper', '헬퍼')], db_index=True, max_length=10, verbose_name='노출 위치')),
                ('writing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='board.Writing', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '노출위치',
                'verbose_name_plural': '노출위치',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_comments', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('writing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.Writing', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '코멘트',
                'verbose_name_plural': '코멘트',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='AttachFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach_file', models.FileField(upload_to='', verbose_name='첨부파일')),
                ('is_active', models.BooleanField(default=True, verbose_name='유효성')),
                ('writing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='board.Writing', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '첨부파일',
                'verbose_name_plural': '첨부파일',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
            ],
            options={
                'verbose_name': '답변',
                'verbose_name_plural': '답변',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('board.comment',),
        ),
        migrations.CreateModel(
            name='ContactWriting',
            fields=[
            ],
            options={
                'verbose_name': '1:1 문의',
                'verbose_name_plural': '1:1 문의',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('board.writing',),
        ),
        migrations.CreateModel(
            name='EventWriting',
            fields=[
            ],
            options={
                'verbose_name': '이벤트',
                'verbose_name_plural': '이벤트',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('board.writing',),
        ),
        migrations.CreateModel(
            name='FAQWriting',
            fields=[
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('board.writing',),
        ),
        migrations.CreateModel(
            name='MagazineWriting',
            fields=[
            ],
            options={
                'verbose_name': '매거진',
                'verbose_name_plural': '매거진',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('board.writing',),
        ),
        migrations.CreateModel(
            name='NoticeWriting',
            fields=[
            ],
            options={
                'verbose_name': '공지',
                'verbose_name_plural': '공지',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('board.writing',),
        ),
        migrations.CreateModel(
            name='PartnershipWriting',
            fields=[
            ],
            options={
                'verbose_name': '제휴/제안',
                'verbose_name_plural': '제휴/제안',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('board.writing',),
        ),
        migrations.CreateModel(
            name='WebtoonWriting',
            fields=[
            ],
            options={
                'verbose_name': '웹툰',
                'verbose_name_plural': '웹툰',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('board.writing',),
        ),
    ]
