# Generated by Django 2.2.7 on 2020-03-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='updated_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수정일시'),
        ),
    ]
