# Generated by Django 2.2.7 on 2020-03-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200310_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleImage',
            fields=[
            ],
            options={
                'verbose_name': '대표 이미지',
                'verbose_name_plural': '대표 이미지',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('board.attachfile',),
        ),
        migrations.RenameField(
            model_name='attachfile',
            old_name='attach_file',
            new_name='attach',
        ),
    ]
