# Generated by Django 2.2.7 on 2020-03-11 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_writing_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('writing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='term', to='board.Writing', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '노출기간',
                'verbose_name_plural': '노출기간',
            },
        ),
    ]
