# Generated by Django 2.2.7 on 2020-07-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_viewterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleWriting',
            fields=[
            ],
            options={
                'verbose_name': '보도자료',
                'verbose_name_plural': '보도자료',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('board.writing',),
        ),
        migrations.AlterField(
            model_name='writing',
            name='board',
            field=models.PositiveSmallIntegerField(choices=[(1, '1:1 문의'), (2, '제휴/제안'), (3, '공지'), (4, '이벤트'), (5, '매거진'), (6, '웹툰'), (7, 'FAQ'), (11, '보도자료')], verbose_name='게시판'),
        ),
    ]
