# Generated by Django 2.2.7 on 2020-03-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyman_migration', '0002_anycodeasis_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anycodeasis',
            name='anycode',
            field=models.CharField(max_length=10, verbose_name='AnyCode'),
        ),
    ]
